# Generated by Django 2.2.10 on 2020-03-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200322_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='degisecek'),
        ),
    ]
